# Generated by Django 5.2.3 on 2025-06-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
