# Generated by Django 5.2.3 on 2025-06-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your site logo here.', null=True, upload_to='site/'),
        ),
    ]
